on: 
  push:
    branches:
      - main

jobs:
  detect-and-deploy-changes:
    name: Detect Changes and Deploy to Mastory
    runs-on: ubuntu-latest
    steps:
      - uses: mastoryberlin/content-action@v0.1.0-rc1
        with:
          scope: gerd
          api_key: ${{ secrets.MASTORY_API_KEY }}