on:
  push:
    branches:
      - main

jobs:
  detect-and-deploy-changes:
    name: Detect Changes and Deploy to Mastory
    runs-on: ubuntu-latest
    steps:
      - uses: mastoryberlin/content-action@main
        with:
          # scope: ${{ vars.MASTORY_SCOPE }} # defaults to your GitHub user name
          api_key: ${{ secrets.MASTORY_API_KEY }}