on: 
  workflow_dispatch:

jobs:
  reinit:
    name: Reinitialize Mastory Content Scope from scratch
    runs-on: ubuntu-latest
    steps:
      - uses: mastoryberlin/content-action@v0.1.0-rc8
        with:
          scope: gerd
          api_key: ${{ secrets.MASTORY_API_KEY }}
          reinit: true